import type { PermissionName, RoleName } from './permission.types';

export const rolePermissions: Record<RoleName, readonly PermissionName[]> = {
  TENANT_ADMIN: [
    'account:user:view',
    'account:user:manage',
    'permission:role:manage',
    'organization:unit:view',
    'organization:unit:manage',
    'employee:profile:view',
    'employee:profile:edit',
    'shift:rule:view',
    'shift:rule:manage',
    'attendance:group:view',
    'attendance:group:manage',
    'attendance:record:view',
    'attendance:record:edit',
    'attendance:result:view',
    'attendance:result:recalculate',
    'attendance:report:export',
    'leave:request:create',
    'leave:request:view',
    'leave:request:approve',
    'repair:request:create',
    'repair:request:view',
    'repair:request:approve',
    'audit-log:view',
  ],
  HR_ADMIN: [
    'organization:unit:view',
    'organization:unit:manage',
    'employee:profile:view',
    'employee:profile:edit',
    'shift:rule:view',
    'shift:rule:manage',
    'attendance:group:view',
    'attendance:group:manage',
    'attendance:record:view',
    'attendance:record:edit',
    'attendance:result:view',
    'attendance:result:recalculate',
    'attendance:report:export',
    'leave:request:create',
    'leave:request:view',
    'leave:request:approve',
    'repair:request:create',
    'repair:request:view',
    'repair:request:approve',
    'audit-log:view',
  ],
  ORG_MANAGER: [
    'organization:unit:view',
    'employee:profile:view',
    'shift:rule:view',
    'attendance:group:view',
    'attendance:record:view',
    'attendance:result:view',
    'leave:request:create',
    'leave:request:view',
    'leave:request:approve',
    'repair:request:create',
    'repair:request:view',
    'repair:request:approve',
  ],
  EMPLOYEE: [
    'employee:profile:view',
    'attendance:checkin:create',
    'attendance:record:view',
    'attendance:result:view',
    'leave:request:create',
    'leave:request:view',
    'repair:request:create',
    'repair:request:view',
  ],
};

export const permissionMetadataKey = Symbol('easy-erp:permission');
